### ISSUE TITLE
AttributeError: 'int' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by SolicTous** [leftthomas/ImageDeblurring#37]
epoch:  1 / 10
batches:  302
2020-11-12 12:18:02.225578: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-11-12 12:18:03.190597: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-11-12 12:18:03.252643: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
Traceback (most recent call last):
  File "/home/developer/PycharmProjects/DeblurGAN-Keras-2/main.py", line 109, in <module>
    train(batch_size=2, epoch_num=10)
  File "/home/developer/PycharmProjects/DeblurGAN-Keras-2/main.py", line 56, in train
    d_loss = d.train_on_batch(x, y)
  File "/home/developer/PycharmProjects/DeblurGAN-Keras/venv/lib/python3.7/site-packages/keras/engine/training.py", line 1843, in train_on_batch
    check_batch_axis=True)
  File "/home/developer/PycharmProjects/DeblurGAN-Keras/venv/lib/python3.7/site-packages/keras/engine/training.py", line 1430, in _standardize_user_data
    exception_prefix='target')
  File "/home/developer/PycharmProjects/DeblurGAN-Keras/venv/lib/python3.7/site-packages/keras/engine/training.py", line 70, in _standardize_input_data
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
  File "/home/developer/PycharmProjects/DeblurGAN-Keras/venv/lib/python3.7/site-packages/keras/engine/training.py", line 70, in <listcomp>
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
AttributeError: 'int' object has no attribute 'ndim'

**Comment by leftthomas** [comment]
@artvizi you should use the old `keras` API

**Comment by SolicTous** [comment]
> 
> 
> @artvizi you should use the old `keras` API

Really - thank you)
