### ISSUE TITLE
does something wrong in x?

### ISSUE THREAD

**Issue by chenyuyi94** [leftthomas/ImageDeblurring#7]
epoch:  1 / 10
batches:  302
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/ImageDeblurring-master/main.py", line 104, in <module>
    train(batch_size=2, epoch_num=10)
  File "C:/Users/Administrator/Desktop/ImageDeblurring-master/main.py", line 51, in train
    d_loss = d.train_on_batch(x, y)
  File "C:\Program Files (x86)\python3.5\lib\site-packages\keras\engine\training.py", line 1843, in train_on_batch
    check_batch_axis=True)
  File "C:\Program Files (x86)\python3.5\lib\site-packages\keras\engine\training.py", line 1430, in _standardize_user_data
    exception_prefix='target')
  File "C:\Program Files (x86)\python3.5\lib\site-packages\keras\engine\training.py", line 70, in _standardize_input_data
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
  File "C:\Program Files (x86)\python3.5\lib\site-packages\keras\engine\training.py", line 70, in <listcomp>
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
AttributeError: 'int' object has no attribute 'ndim'

**Comment by leftthomas** [comment]
@chenyuyi94 check your train images， and debug for that，I have used this code to train， it's OK.

**Comment by chenyuyi94** [comment]
Thank you for your reply.The train images do not under the folder of [ImageDeblurring/data/small/train/]

**Comment by longndmta** [comment]
Sorry. I’m being in the same error. Can u help me? 
Thank you.
