### ISSUE TITLE
invalid length error

### ISSUE THREAD

**Issue by xihu2012y** [leftthomas/ImageDeblurring#9]
Hi,

I installed the repo on my notebook. After run python data_utils.py, I run python main.py. Following is 
error message.

epoch: epoch: Traceback (most recent call last):
  File "main.py", line 104, in <module>
    train(batch_size=2, epoch_num=10)
  File "main.py", line 29, in train
    print('epoch: ', epoch + 1, '/', epoch_num)
  File "D:\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "D:\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "D:\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "D:\Anaconda3\lib\site-packages\colorama\ansitowin32.py", line 175, in write_plain_text
    self.wrapped.flush()
OSError: raw write() returned invalid length 14 (should have been between 0 and 7)

**Comment by leftthomas** [comment]
@xihu2012y ，it’s the problem of tqdm, make sure you know the usage of tqdm, it has different between raw python and notebook python.
